# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  # aliased to 5.2.17
  - 5.2
  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5

before_script:
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.2' ]; then pyrus install http://phptal.org/latest.tar.gz && pear install pear/PHP_CodeSniffer && phpenv rehash; fi"

script:
  - phpunit --configuration phpunit.xml --coverage-text
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.5' ]; then phpcs --standard=psr1 --encoding=UTF-8 --report=summary -p; fi"
