# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  # aliased to 5.2.17
  - 5.2
  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5

matrix:
  allow_failures:
    - php: 5.4
      env:
        - PHPCS=1
  include:
    - php: 5.4
      env:
        - PHPCS=1

before_script:
  - pear channel-discover pear.cakephp.org
  - pear install --alldeps cakephp/CakePHP_CodeSniffer
  - phpenv rehash
  # - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.2' ]; then pyrus install http://phptal.org/latest.tar.gz && pear install pear/PHP_CodeSniffer && phpenv rehash; fi"

script:
  - phpunit --configuration phpunit.xml --coverage-text
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.5' ]; then phpcs --standard=psr1; fi"

notifications:
  email: false